name: pytest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io://dataoneorg/slinky:latest
    steps:
    - uses: actions/checkout@v3
    - run: python -m pip install .[test]
    - run: python -m pytest
